import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

export type Language = "en" | "es" | "fr" | "de" | "ja" | "ko" | "zh" | "pt" | "ar" | "hi"

export const LANGUAGES: { code: Language; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "es", label: "Spanish", native: "Español" },
  { code: "fr", label: "French", native: "Français" },
  { code: "de", label: "German", native: "Deutsch" },
  { code: "ja", label: "Japanese", native: "日本語" },
  { code: "ko", label: "Korean", native: "한국어" },
  { code: "zh", label: "Chinese", native: "中文" },
  { code: "pt", label: "Portuguese", native: "Português" },
  { code: "ar", label: "Arabic", native: "العربية" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
]

interface LanguageContextValue {
  lang: Language
  setLang: (l: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem("nya-lang") as Language) || "en"
  })

  useEffect(() => {
    localStorage.setItem("nya-lang", lang)
    document.documentElement.lang = lang
    if (lang === "ar") document.documentElement.dir = "rtl"
    else document.documentElement.dir = "ltr"
  }, [lang])

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider")
  return ctx
}

const translations: Record<string, Record<string, string>> = {
  en: {
    "nav.how_it_works": "How it works",
    "nav.features": "Features",
    "nav.contact": "Contact",
    "nav.sign_in": "Sign In",
    "nav.get_started": "Get started",
    "nav.back_to_home": "Back to home",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "hero.title": "Ask your\ncompany docs",
    "hero.subtitle": "Upload documents. Ask questions in plain English. Get answers with source citations.",
    "hero.cta": "Get started free",
    "hero.see": "See how it works",
    "contact.title": "Contact us",
    "contact.subtitle": "Get in touch with the NyaAI team.",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.send": "Send message",
    "contact.sent_title": "Message sent!",
    "contact.sent_desc": "We'll get back to you as soon as possible.",
    "contact.send_another": "Send another message",
    "privacy.title": "Privacy Policy",
    "terms.title": "Terms of Service",
    "lang.select": "Select language",
  },
  es: {
    "nav.how_it_works": "Cómo funciona",
    "nav.features": "Características",
    "nav.contact": "Contacto",
    "nav.sign_in": "Iniciar sesión",
    "nav.get_started": "Comenzar",
    "nav.back_to_home": "Volver al inicio",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.contact": "Contacto",
    "footer.rights": "Todos los derechos reservados.",
    "hero.title": "Pregunta a tus\ndocumentos",
    "hero.subtitle": "Sube documentos. Haz preguntas en lenguaje natural. Obtén respuestas con citas de fuentes.",
    "hero.cta": "Comienza gratis",
    "hero.see": "Ver cómo funciona",
    "contact.title": "Contáctanos",
    "contact.subtitle": "Ponte en contacto con el equipo de NyaAI.",
    "contact.name": "Nombre",
    "contact.email": "Correo electrónico",
    "contact.message": "Mensaje",
    "contact.send": "Enviar mensaje",
    "contact.sent_title": "¡Mensaje enviado!",
    "contact.sent_desc": "Te responderemos lo antes posible.",
    "contact.send_another": "Enviar otro mensaje",
    "privacy.title": "Política de Privacidad",
    "terms.title": "Términos del Servicio",
    "lang.select": "Seleccionar idioma",
  },
  fr: {
    "nav.how_it_works": "Comment ça marche",
    "nav.features": "Fonctionnalités",
    "nav.contact": "Contact",
    "nav.sign_in": "Se connecter",
    "nav.get_started": "Commencer",
    "nav.back_to_home": "Retour à l'accueil",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés.",
    "hero.title": "Interrogez vos\ndocuments d'entreprise",
    "hero.subtitle": "Téléchargez des documents. Posez des questions en langage naturel. Obtenez des réponses avec citations.",
    "hero.cta": "Commencez gratuitement",
    "hero.see": "Voir comment ça marche",
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Entrez en contact avec l'équipe NyaAI.",
    "contact.name": "Nom",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.send": "Envoyer",
    "contact.sent_title": "Message envoyé !",
    "contact.sent_desc": "Nous vous répondrons dans les plus brefs délais.",
    "contact.send_another": "Envoyer un autre message",
    "privacy.title": "Politique de Confidentialité",
    "terms.title": "Conditions d'Utilisation",
    "lang.select": "Choisir la langue",
  },
  de: {
    "nav.how_it_works": "So funktioniert's",
    "nav.features": "Funktionen",
    "nav.contact": "Kontakt",
    "nav.sign_in": "Anmelden",
    "nav.get_started": "Loslegen",
    "nav.back_to_home": "Zurück zur Startseite",
    "footer.privacy": "Datenschutz",
    "footer.terms": "AGB",
    "footer.contact": "Kontakt",
    "footer.rights": "Alle Rechte vorbehalten.",
    "hero.title": "Fragen Sie Ihre\nUnternehmensdokumente",
    "hero.subtitle": "Dokumente hochladen. Fragen in natürlicher Sprache stellen. Antworten mit Quellenangaben erhalten.",
    "hero.cta": "Kostenlos starten",
    "hero.see": "So funktioniert's",
    "contact.title": "Kontaktieren Sie uns",
    "contact.subtitle": "Nehmen Sie Kontakt mit dem NyaAI-Team auf.",
    "contact.name": "Name",
    "contact.email": "E-Mail",
    "contact.message": "Nachricht",
    "contact.send": "Nachricht senden",
    "contact.sent_title": "Nachricht gesendet!",
    "contact.sent_desc": "Wir werden uns so schnell wie möglich bei Ihnen melden.",
    "contact.send_another": "Weitere Nachricht senden",
    "privacy.title": "Datenschutzerklärung",
    "terms.title": "Nutzungsbedingungen",
    "lang.select": "Sprache auswählen",
  },
  ja: {
    "nav.how_it_works": "使い方",
    "nav.features": "機能",
    "nav.contact": "お問い合わせ",
    "nav.sign_in": "ログイン",
    "nav.get_started": "始める",
    "nav.back_to_home": "ホームに戻る",
    "footer.privacy": "プライバシー",
    "footer.terms": "利用規約",
    "footer.contact": "お問い合わせ",
    "footer.rights": "All rights reserved.",
    "hero.title": "社内文書に\n質問する",
    "hero.subtitle": "文書をアップロードして、自然言語で質問。ソース付きの回答を即座に取得。",
    "hero.cta": "無料で始める",
    "hero.see": "使い方を見る",
    "contact.title": "お問い合わせ",
    "contact.subtitle": "NyaAIチームにご連絡ください。",
    "contact.name": "お名前",
    "contact.email": "メールアドレス",
    "contact.message": "メッセージ",
    "contact.send": "送信",
    "contact.sent_title": "メッセージを送信しました！",
    "contact.sent_desc": "できるだけ早くご連絡いたします。",
    "contact.send_another": "別のメッセージを送信",
    "privacy.title": "プライバシーポリシー",
    "terms.title": "利用規約",
    "lang.select": "言語を選択",
  },
  ko: {
    "nav.how_it_works": "사용 방법",
    "nav.features": "기능",
    "nav.contact": "문의하기",
    "nav.sign_in": "로그인",
    "nav.get_started": "시작하기",
    "nav.back_to_home": "홈으로 돌아가기",
    "footer.privacy": "개인정보처리방침",
    "footer.terms": "이용약관",
    "footer.contact": "문의하기",
    "footer.rights": "All rights reserved.",
    "hero.title": "회사 문서에\n질문하세요",
    "hero.subtitle": "문서를 업로드하고 자연어로 질문하세요. 출처가 포함된 답변을 받아보세요.",
    "hero.cta": "무료로 시작하기",
    "hero.see": "사용 방법 보기",
    "contact.title": "문의하기",
    "contact.subtitle": "NyaAI 팀에 연락하세요.",
    "contact.name": "이름",
    "contact.email": "이메일",
    "contact.message": "메시지",
    "contact.send": "보내기",
    "contact.sent_title": "메시지가 전송되었습니다!",
    "contact.sent_desc": "최대한 빨리 답변 드리겠습니다.",
    "contact.send_another": "다른 메시지 보내기",
    "privacy.title": "개인정보 처리방침",
    "terms.title": "이용약관",
    "lang.select": "언어 선택",
  },
  zh: {
    "nav.how_it_works": "使用方法",
    "nav.features": "功能",
    "nav.contact": "联系我们",
    "nav.sign_in": "登录",
    "nav.get_started": "开始使用",
    "nav.back_to_home": "返回首页",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.contact": "联系我们",
    "footer.rights": "All rights reserved.",
    "hero.title": "向您的\n公司文档提问",
    "hero.subtitle": "上传文档，用自然语言提问，获取带来源引用的答案。",
    "hero.cta": "免费开始",
    "hero.see": "查看使用方法",
    "contact.title": "联系我们",
    "contact.subtitle": "与NyaAI团队取得联系。",
    "contact.name": "姓名",
    "contact.email": "邮箱",
    "contact.message": "留言",
    "contact.send": "发送消息",
    "contact.sent_title": "消息已发送！",
    "contact.sent_desc": "我们会尽快回复您。",
    "contact.send_another": "再发一条消息",
    "privacy.title": "隐私政策",
    "terms.title": "服务条款",
    "lang.select": "选择语言",
  },
  pt: {
    "nav.how_it_works": "Como funciona",
    "nav.features": "Recursos",
    "nav.contact": "Contato",
    "nav.sign_in": "Entrar",
    "nav.get_started": "Começar",
    "nav.back_to_home": "Voltar ao início",
    "footer.privacy": "Privacidade",
    "footer.terms": "Termos",
    "footer.contact": "Contato",
    "footer.rights": "Todos os direitos reservados.",
    "hero.title": "Pergunte aos seus\ndocumentos corporativos",
    "hero.subtitle": "Envie documentos. Faça perguntas em linguagem natural. Obtenha respostas com citações.",
    "hero.cta": "Comece grátis",
    "hero.see": "Veja como funciona",
    "contact.title": "Fale conosco",
    "contact.subtitle": "Entre em contato com a equipe NyaAI.",
    "contact.name": "Nome",
    "contact.email": "Email",
    "contact.message": "Mensagem",
    "contact.send": "Enviar",
    "contact.sent_title": "Mensagem enviada!",
    "contact.sent_desc": "Responderemos o mais breve possível.",
    "contact.send_another": "Enviar outra mensagem",
    "privacy.title": "Política de Privacidade",
    "terms.title": "Termos de Serviço",
    "lang.select": "Selecionar idioma",
  },
}

// Arabic translations
translations["ar"] = {
  "nav.how_it_works": "كيف يعمل",
  "nav.features": "الميزات",
  "nav.contact": "اتصل بنا",
  "nav.sign_in": "تسجيل الدخول",
  "nav.get_started": "ابدأ الآن",
  "nav.back_to_home": "العودة إلى الصفحة الرئيسية",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.contact": "اتصل بنا",
  "footer.rights": "جميع الحقوق محفوظة.",
  "hero.title": "اسأل\nمستندات شركتك",
  "hero.subtitle": "حمّل المستندات. اطرح الأسئلة بلغة طبيعية. احصل على إجابات مع اقتباسات المصادر.",
  "hero.cta": "ابدأ مجاناً",
  "hero.see": "شاهد كيف يعمل",
  "contact.title": "اتصل بنا",
  "contact.subtitle": "تواصل مع فريق NyaAI.",
  "contact.name": "الاسم",
  "contact.email": "البريد الإلكتروني",
  "contact.message": "الرسالة",
  "contact.send": "إرسال",
  "contact.sent_title": "تم إرسال الرسالة!",
  "contact.sent_desc": "سنعود إليك في أقرب وقت ممكن.",
  "contact.send_another": "إرسال رسالة أخرى",
  "privacy.title": "سياسة الخصوصية",
  "terms.title": "شروط الخدمة",
  "lang.select": "اختر اللغة",
}

// Hindi translations
translations["hi"] = {
  "nav.how_it_works": "यह कैसे काम करता है",
  "nav.features": "विशेषताएँ",
  "nav.contact": "संपर्क करें",
  "nav.sign_in": "साइन इन करें",
  "nav.get_started": "शुरू करें",
  "nav.back_to_home": "होम पर वापस जाएँ",
  "footer.privacy": "गोपनीयता",
  "footer.terms": "शर्तें",
  "footer.contact": "संपर्क",
  "footer.rights": "सर्वाधिकार सुरक्षित।",
  "hero.title": "अपने कंपनी\nदस्तावेज़ों से पूछें",
  "hero.subtitle": "दस्तावेज़ अपलोड करें। सरल भाषा में प्रश्न पूछें। स्रोत उद्धरण के साथ उत्तर प्राप्त करें।",
  "hero.cta": "मुफ्त शुरू करें",
  "hero.see": "देखें यह कैसे काम करता है",
  "contact.title": "संपर्क करें",
  "contact.subtitle": "NyaAI टीम से संपर्क करें।",
  "contact.name": "नाम",
  "contact.email": "ईमेल",
  "contact.message": "संदेश",
  "contact.send": "भेजें",
  "contact.sent_title": "संदेश भेज दिया गया!",
  "contact.sent_desc": "हम जल्द से जल्द आपसे संपर्क करेंगे।",
  "contact.send_another": "दूसरा संदेश भेजें",
  "privacy.title": "गोपनीयता नीति",
  "terms.title": "सेवा की शर्तें",
  "lang.select": "भाषा चुनें",
}
